### Create token - invalid user key

POST {{GeoService.HostAddress}}/api/tokens
Content-Type: application/json

{
  "UserKey": "drinkjuice" 
}

### Create token - success

POST {{GeoService.HostAddress}}/api/tokens
Content-Type: application/json

{
  "UserKey": "drinkwater"
}

> {%
    client.global.set("token", response.body.token);
%}

### Create country - success

POST {{GeoService.HostAddress}}/api/countries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Acronym": "BR",
  "Name": "Brazil",
  "Continent": "South America",
  "Cities": [
    {
      "Name": "Sao Paulo",
      "Population": "11904961"
    },
    {
      "Name": "Rio de Janeiro",
      "Population": "6730729"
    }
  ]
}

### Get country - success

GET {{GeoService.HostAddress}}/api/countries/BR
Accept: application/json
Authorization: Bearer {{token}}

### Get country - country not found

GET {{GeoService.HostAddress}}/api/countries/NF
Accept: application/json
Authorization: Bearer {{token}}

### Update country

PUT {{GeoService.HostAddress}}/api/countries/BR
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Cities": [
    {
      "Name": "Marilia",
      "Population": "247348"
    },
    {
      "Name": "Brasilia",
      "Population": "2716381"
    }
  ]
}

### Delete country

DELETE {{GeoService.HostAddress}}/api/countries/BR
Content-Type: application/json
Authorization: Bearer {{token}}